---
- hosts: vpn
  become: yes
  tasks:

    - name: Install WireGuard
      apt:
        name: wireguard
        state: present
        update_cache: yes

    - name: Generate server private key
      command: wg genkey
      register: server_private_key

    - name: Generate server public key
      command: echo "{{ server_private_key.stdout }}" | wg pubkey
      register: server_public_key

    - name: Create WireGuard server configuration
      template:
        src: wireguard.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: 0600

    - name: Enable and start WireGuard
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started

    - name: Create client configuration
      template:
        src: client.conf.j2
        dest: ~/client-wg.conf
